//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace New_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentsData
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int Age { get; set; }
        public System.DateTime Dob { get; set; }
        public string Email { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public bool IsArchived { get; set; }
    }
}
